### ISSUE TITLE
Missing :IDatabaseConnection inheritance

### ISSUE THREAD

**Issue by MatthewWelch** [AlessandroDelSole/XamarinFormsStarterKit#1]
Thanks for this starter kit. Out of the box the iOS project failed for me with null object reference. Looks the the DatabaseConnection_iOS class may be missing the inheritance of the IDatabaseConnection interface. After adding it (public class DatabaseConnection_iOS : IDatabaseConnection ) it worked fine.

Hope this helps

**Comment by AlessandroDelSole** [comment]
Thank you very much for reporting this and sorry for the inconvenience. I have fixed the issue and submitted an updated file.
